import { describe, expect, it } from 'vitest';
import type { NormalizedPlatformConfig } from '../src/config/types.js';
import { LogAnalyzer } from '../src/services/log-analyzer.js';

const config: NormalizedPlatformConfig = {
  name: 'Homebridge Health Monitor',
  logFile: '/tmp/homebridge.log',
  scanIntervalSeconds: 5,
  analysisWindowSeconds: 300,
  resetAfterSeconds: 600,
  errorThreshold: 3,
  monitorWarnings: false,
  debug: false,
};

describe('LogAnalyzer', () => {
  it('counts ERROR lines as anomalies', () => {
    const analyzer = new LogAnalyzer(config);

    const anomaly = analyzer.ingest('[23/07/2026, 10:00:00] [homebridge-test] [ERROR] failed to connect', 1_000);

    expect(anomaly).toMatchObject({
      severity: 'error',
      pluginName: 'homebridge-test',
      message: 'failed to connect',
    });
    expect(analyzer.snapshot(2_000).anomalyCount).toBe(1);
  });

  it('ignores WARN lines by default', () => {
    const analyzer = new LogAnalyzer(config);

    analyzer.ingest('[homebridge-test] [WARN] retrying', 1_000);

    expect(analyzer.snapshot(2_000).anomalyCount).toBe(0);
  });

  it('counts WARN lines when warning monitoring is enabled', () => {
    const analyzer = new LogAnalyzer({
      ...config,
      monitorWarnings: true,
    });

    const anomaly = analyzer.ingest('[homebridge-test] [WARN] retrying', 1_000);

    expect(anomaly?.severity).toBe('warning');
    expect(analyzer.snapshot(2_000).anomalyCount).toBe(1);
  });

  it('ignores logs generated by this plugin', () => {
    const analyzer = new LogAnalyzer(config);

    analyzer.ingest('[Homebridge Health Monitor] [ERROR] Health Monitor alert active', 1_000);
    analyzer.ingest('[homebridge-health-monitor] [ERROR] Health Monitor alert active', 2_000);

    expect(analyzer.snapshot(3_000).anomalyCount).toBe(0);
  });

  it('activates the alert when the threshold is reached', () => {
    const analyzer = new LogAnalyzer(config);

    analyzer.ingest('[homebridge-a] [ERROR] first', 1_000);
    analyzer.ingest('[homebridge-a] [ERROR] second', 2_000);
    analyzer.ingest('[homebridge-a] [ERROR] third', 3_000);

    expect(analyzer.snapshot(4_000)).toMatchObject({
      anomalyCount: 3,
      alertActive: true,
    });
  });

  it('prunes anomalies outside the rolling window', () => {
    const analyzer = new LogAnalyzer({
      ...config,
      analysisWindowSeconds: 10,
    });

    analyzer.ingest('[homebridge-a] [ERROR] first', 1_000);
    analyzer.ingest('[homebridge-a] [ERROR] second', 11_000);

    expect(analyzer.snapshot(11_000).anomalyCount).toBe(2);
    expect(analyzer.snapshot(11_001).anomalyCount).toBe(1);
  });
});
